[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.proxyProtocol]
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.proxyProtocol]

[providers]
  [providers.kubernetesIngress]
    ingressClass = "traefik"
  [providers.file]
    filename = "/etc/traefik/file_provider.toml"
[api]
  insecure = true
  dashboard = true

[ping]
  entryPoint = "http"

[log]
  level = "INFO"

[accessLog]
